[package]
name = "tjiftjaf"
version = "0.0.1"
edition = "2024"

[dependencies]
async-broadcast = { version = "0.7.2", default-features = false }
async-channel = { version = "2.5.0", default-features = false }
bytes = { version = "1.10.1", default-features = false, features = ["std"] }
futures-lite = { version = "2.6.0", default-features = false, features = ["std", "race"] }
log = "0.4.27"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
async-io = { version = "2.4.1", default-features = false }

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3.77"
wasm-bindgen = "0.2.100"
wasm-bindgen-futures = "0.4.50"
web-time = "1.1.0"

[dev-dependencies]
simple_logger = "5.0.0"
macro_rules_attribute = "0.2.2"
pretty_assertions = { version = "1.4.1", default-features = false, features = ["std"] }
rumqttd = { version = "0.19.0", default-features = false }
smol-macros = "0.1.1"
async-net = { version = "2.0.0", default-features = false }
smol = { version = "2.0.2", default-features = false }
