name: Test and lint

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    timeout-minutes: 5
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@1.92.0
        with:
          components: clippy,rustfmt

      - name: Run lint script
        run: bash scripts/lint.sh

  test:
    timeout-minutes: 5
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@1.92.0

      - name: Run tests
        run: bash scripts/test.sh

  fuzz:
    timeout-minutes: 5
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@nightly

      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz

      - name: Build fuzz targets
        run: cargo +nightly fuzz build
